name: maven publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java-version: [11]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: deploy
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
