name: Maven Publish

on:
  workflow_dispatch: # for debug
  push:
    branches: [main]
    tags:
      - v*.*.*

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Setup java environment
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          java-version: 11
          distribution: "adopt"
          cache: maven

      - name: Upload package to registry
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
