name: Maven CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 15 * * 0"

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: # for EnricoMi/publish-unit-test-result-action
      checks: write
      pull-requests: write # for comment_mode
      contents: read # only for private repository
      issues: read # only for private repository
    strategy:
      matrix:
        java-version: [11]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: Setup java environment
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: maven

      - name: Lint java code by checkstyle
        uses: nikitasavinov/checkstyle-action@79490c0fdcc3ab5dd2b50a0e82a5bfc4fe63f0a9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-check"

      - name: Build by maven
        run: mvn -B package --file pom.xml

      - name: Publish junit report to PR
        uses: EnricoMi/publish-unit-test-result-action@689e79fca56cb0c3117fbb26e9769b4634a3f521
        if: ${{ env.os == 'ubuntu-latest' }} # linux is only supported
        with:
          check_name: junit test results
          files: target/surefire-reports/**/*.xml

      - name: Move target files
        run: mkdir staging && cp target/*.jar staging

      - name: Upload junit report to artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: Package
          path: staging

  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["java"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: Initialize CodeQL
        uses: github/codeql-action/init@168b99b3c22180941ae7dbdd5f5c9678ede476ba
        with:
          languages: ${{ matrix.language }}

      - name: Build automatically
        uses: github/codeql-action/autobuild@168b99b3c22180941ae7dbdd5f5c9678ede476ba

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@168b99b3c22180941ae7dbdd5f5c9678ede476ba
