name: maven publish

on:
  push:
#     tags:
#       - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java-version: [11]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: build
        run: mvn -B package --file pom.xml
      - name: deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
